language: node_js
node_js:
  - "lts/*"
branches:
  only:
    - master

jobs:
  include:
    - stage: Produce Coverage
      script: tap test/*.js --coverage-report=lcov && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
