# Adapted coveralls_simple
# https://circleci.com/developer/orbs/orb/coveralls/coveralls#commands
version: 2.1

orbs:
    coveralls: coveralls/coveralls@1.0.6

jobs:
    build:
        docker:
            - image: 'cimg/node:20.10.0'
        steps:
            - checkout
            - run:
                  name: Install and Test
                  command: npm install && npm test --path_to_lcov=/.tap/report/lcov.info
            - coveralls/upload:
                  token: COVERALLS_REPO_TOKEN
                  verbose: true
