# Adapted coveralls_simple
# https://circleci.com/developer/orbs/orb/coveralls/coveralls#commands
version: 2.1

orbs:
    coveralls: coveralls/coveralls@2.2.5

jobs:
    build:
        docker:
            - image: 'cimg/node:20.18.0'
        steps:
            - checkout
            - run:
                  name: Install and Test
                  command: npm install && npm run coverage
            - coveralls/upload:
                  token: COVERALLS_REPO_TOKEN
                  verbose: true
