# Adapted coveralls_simple
# https://circleci.com/developer/orbs/orb/coveralls/coveralls#commands
version: 2.1

orbs:
    coveralls: coveralls/coveralls@1.0.6

jobs:
    build:
        docker:
            - image: 'circleci/node:14.16.0'
        steps:
            - checkout
            - run:
                  name: Install and Test
                  command: npm install && node ./cli.js .nyc_output && tap test/*.js
            - coveralls/upload:
                  token: COVERALLS_REPO_TOKEN
                  verbose: true
